language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
dist: xenial
sudo: true
# Command to install dependencies
install:
  - python setup.py install
  - pip install --upgrade pytest 
  - pip install -r dev-requirements.txt
# Command to run tests
script:
  - py.test -s --cov-report=xml --cov
# Command after success
after_success:
  - python-codacy-coverage -r coverage.xml