
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftANDORAND CONDITION GT LPAREN LT NUMBER OR RPARENstatement : expressionexpression : LPAREN expression RPAREN\n        expression : expression AND expression\n                    | expression OR expression\n        \n        expression : CONDITION LT NUMBER\n                    | CONDITION GT NUMBER\n        '
    
_lr_action_items = {'LPAREN':([0,3,5,6,],[3,3,3,3,]),'CONDITION':([0,3,5,6,],[4,4,4,4,]),'$end':([1,2,10,11,12,13,14,],[0,-1,-3,-4,-2,-5,-6,]),'AND':([2,7,10,11,12,13,14,],[5,5,-3,-4,-2,-5,-6,]),'OR':([2,7,10,11,12,13,14,],[6,6,-3,-4,-2,-5,-6,]),'LT':([4,],[8,]),'GT':([4,],[9,]),'RPAREN':([7,10,11,12,13,14,],[12,-3,-4,-2,-5,-6,]),'NUMBER':([8,9,],[13,14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,3,5,6,],[2,7,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement','conditionparser.py',36),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_sub_expression','conditionparser.py',41),
  ('expression -> expression AND expression','expression',3,'p_and_or_expression','conditionparser.py',46),
  ('expression -> expression OR expression','expression',3,'p_and_or_expression','conditionparser.py',47),
  ('expression -> CONDITION LT NUMBER','expression',3,'p_relation_expression','conditionparser.py',56),
  ('expression -> CONDITION GT NUMBER','expression',3,'p_relation_expression','conditionparser.py',57),
]
