# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# https://docs.github.com/cn/actions/learn-github-actions/contexts#github-context
name: autoremove-torrents

on:
  push:
    branches:
      - master
      - dev
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: BuildDockerImage
        run: docker build . --file Dockerfile --tag twwch/action-ci:${{ github.ref_name	 }}
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: w12725/autoremove-torrents:${{ github.ref_name	 }}
          repository: w12725/autoremove-torrents
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
